import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "en" | "nb";
export type AppTheme = "light" | "dark" | "system";

type TranslationKey = string;

const STORAGE_KEY = "freshtrack-app-preferences";

const TRANSLATIONS: Record<AppLanguage, Record<TranslationKey, string>> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.food": "My Food",
    "nav.scan": "Scan Barcode",
    "nav.shopping": "Shopping List",
    "nav.deals": "Deals and Prices",
    "nav.recipes": "Recipes",
    "nav.waste": "Waste Tracker",
    "nav.settings": "Settings",
    "settings.title": "Settings",
    "settings.subtitle": "Manage your household and preferences",
    "settings.appearanceLanguage": "Appearance and Language",
    "settings.appearanceTitle": "App Preferences",
    "settings.appearanceDescription": "Choose the interface language and how FreshTrack should handle light or dark mode.",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.themeLight": "Light",
    "settings.themeDark": "Dark",
    "settings.themeSystem": "System",
    "settings.languageEnglish": "English",
    "settings.languageNorwegian": "Norwegian Bokmal",
    "settings.savedLocally": "Saved on this device and applied immediately.",
    "dashboard.kicker": "Dashboard",
    "dashboard.title": "Today’s fridge report.",
    "dashboard.subtitle": "The useful version of opening the fridge three times and hoping it tells you what to cook.",
    "dashboard.totalItems": "Total Items",
    "dashboard.inFridge": "In Fridge",
    "dashboard.inFreezer": "In Freezer",
    "dashboard.expiringSoon": "Expiring Soon",
    "dashboard.useSoon": "Use These Soon",
    "dashboard.viewAll": "View all",
    "dashboard.nextReminder": "Next Reminder",
    "dashboard.tuneSettings": "Tune settings",
    "dashboard.groceryInsights": "Grocery Insights",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.manageFood": "Manage Food",
    "dashboard.manageFoodDesc": "Add, edit, or remove items from your inventory",
    "dashboard.scanBarcode": "Scan Barcode",
    "dashboard.scanBarcodeDesc": "Quick-add items by scanning product barcodes",
    "dashboard.findRecipes": "Find Recipes",
    "dashboard.findRecipesDesc": "Discover what you can cook with what you have",
    "dashboard.open": "Open",
    "shopping.title": "Shopping List",
    "shopping.remaining": "remaining",
    "shopping.cheapestOverall": "Cheapest overall",
    "shopping.checking": "Checking…",
    "shopping.pasteList": "Paste List",
    "shopping.addItem": "Add Item",
    "shopping.newList": "New List",
    "shopping.rename": "Rename",
    "shopping.setDefault": "Set Default",
    "shopping.delete": "Delete",
    "shopping.groceryRecap": "Grocery recap",
    "shopping.boughtThisMonth": "Bought this month",
    "shopping.mostBoughtCategory": "Most bought category",
    "shopping.estimatedSpend": "Estimated spend",
    "shopping.topRepeatedItem": "Top repeated item",
    "shopping.quickAddPlaceholder": "Type item name and press Enter",
    "shopping.storeMode": "Store mode",
    "shopping.storeModeDesc": "Focus on unchecked items with bigger mobile actions.",
    "shopping.on": "On",
    "shopping.off": "Off",
    "shopping.category": "Category",
    "shopping.storeLayout": "Store Layout",
    "shopping.sortedByAisle": "Sorted by aisle order",
    "shopping.emptyTitle": "Your shopping list is empty",
    "shopping.emptyDescription": "Add items or let FreshTrack suggest restocks from your inventory.",
    "shopping.addFirstItem": "Add First Item",
    "shopping.checked": "Checked",
    "shopping.putAwayBought": "Put Away Bought Items",
    "shopping.clearAll": "Clear all",
    "shopping.smartRestock": "Smart Restock",
    "shopping.suggestedRestocks": "Suggested Restocks",
    "shopping.expiringRestock": "Expiring Soon — restock?",
    "shopping.seasonalHolidays": "Seasonal and Holidays",
    "shopping.inSeasonNow": "In Season Now",
    "shopping.inSeasonHint": "typically cheaper and fresher",
    "shopping.browseHolidayLists": "Browse all holiday lists",
    "shopping.createList": "Create Shopping List",
    "shopping.createListSubtitle": "Keep separate lists for different missions",
    "shopping.cancel": "Cancel",
    "shopping.create": "Create List",
    "shopping.pasteTitle": "Paste Shopping List",
    "shopping.pasteSubtitle": "Preview copied notes, comma-separated lists, or one item per line before importing",
    "shopping.previewItems": "Preview Items",
    "shopping.import": "Import",
    "shopping.items": "Items",
    "shopping.putAwaySubtitle": "Choose where each item goes and preview its expiry date",
    "shopping.destination": "Destination",
    "shopping.expiryEstimate": "Expiry estimate",
    "shopping.confirmPutAway": "Confirm Put Away",

    // deals
    "deals.eyebrow": "Section · Market Watch",
    "deals.title": "Deals & Prices",
    "deals.subtitle": "A daily ledger of Norwegian grocery prices, filed via Kassalapp.",
    "deals.tabDeals": "Deals",
    "deals.tabDrops": "Drops",
    "deals.tabSearch": "Search",
    "deals.tabStores": "Stores",
    "deals.bestBasket": "Front page · best basket",
    "deals.kroner": "kroner",
    "deals.runnersUp": "Runners-up · ledger",
    "deals.itemsOf": "of",
    "deals.items": "items",
    "deals.filterChains": "Filter chains",
    "deals.clear": "Clear",
    "deals.addToList": "Add to list",
    "deals.usePrice": "Use price",
    "deals.best": "Best",
    "deals.loadingDeals": "Cross-referencing your basket against the wires…",
    "deals.loadingDrops": "Scanning the wires for price drops…",
    "deals.loadingSearch": "Searching prices…",
    "deals.searchPlaceholder": "Search the Norwegian aisles…",
    "deals.fileSearch": "File search",
    "deals.noDrops": "No price drops filed",
    "deals.noDropsBody": "Nothing significantly cheaper has crossed the wire in the last 30 days.",
    "deals.noDeals": "No deals to file",
    "deals.noDealsBody": "Add items to your shopping list first, then return for the day's best prices.",
    "deals.noProducts": "No products found",
    "deals.noProductsBody": "Try a different search term.",
    "deals.noStoreMatch": "No products match the selected stores.",
    "deals.storesNearbyKicker": "Section · Stores nearby",
    "deals.storesNearbyTitle": "Locate the closest aisles.",
    "deals.storesNearbyBody": "Use your location to map every Norwegian grocery chain within a five kilometre radius.",
    "deals.gettingLocation": "Getting location…",
    "deals.findingStores": "Finding stores…",
    "deals.useMyLocation": "Use my location",
    "deals.refresh": "Refresh",
    "deals.noStores": "No stores nearby",
    "deals.noStoresBody": "Try expanding your search radius.",
    "deals.stopPress": "Stop press",
    "deals.configNeeded": "Configuration needed",
    "deals.somethingWrong": "Something went wrong",
    "deals.getFreeKey": "Get a free API key at",
    "deals.options": "option",
    "deals.optionsPlural": "options",
    "deals.directions": "Directions",
    "deals.within5km": "within 5 km",
    "deals.sessionExpired": "Session expired, redirecting to login…",
    "deals.dropsHeader": "drops in the last 30 days",
    "deals.plateDropsKicker": "Plate · 02 · drops in the last 30 days",
    "deals.plateStoresKicker": "Plate · 04 · within 5 km",
    "deals.itemPrefix": "Item ·",
    "deals.notice": "Notice",
    "deals.toastAddedSuffix": "added to shopping list",
    "deals.toastFailedAdd": "Failed to add to list",
    "deals.toastPriceFiled": "Price filed to shopping list",
    "deals.toastFailedSave": "Failed to save price",
    "deals.toastFailedFindStores": "Failed to find stores",
    "deals.toastGeoNotSupported": "Geolocation is not supported by your browser",
    "deals.toastLocationFailed": "Could not get your location",

    // scan
    "scan.title": "Scan Barcode",
    "scan.subtitle": "Point your camera at a product barcode to quickly add it",
    "scan.opticalKicker": "Optical · barcode capture",
    "scan.statusLive": "live",
    "scan.statusReady": "ready",
    "scan.statusFault": "fault",
    "scan.statusIdle": "idle",
    "scan.scanning": "Scanning",
    "scan.cameraPreview": "Camera preview appears here",
    "scan.aimAtBarcode": "Aim at a product barcode",
    "scan.startCamera": "Start camera",
    "scan.cameraUnavailable": "Camera unavailable",
    "scan.tryAgain": "Try again",
    "scan.stop": "Stop",
    "scan.lookingUp": "looking up product",
    "scan.orEnterManually": "Or · enter manually",
    "scan.typeBarcode": "Type the barcode",
    "scan.lookUp": "Look up",
    "scan.skipManual": "Skip · add item manually",
    "scan.addScannedItem": "Add Scanned Item",
    "scan.addItemManually": "Add Item Manually",
    "scan.barcodePrefix": "Barcode",
    "scan.barcodePlaceholder": "0 0 0 0 0 0 0 0 0 0 0 0",
    "scan.cameraError": "Camera access denied. Please allow camera permissions to scan barcodes.",
    "scan.toastFailedAdd": "Failed to add item",

    // waste
    "waste.title": "Waste Ledger",
    "waste.subtitle": "An honest accounting of what didn't make it to the table",
    "waste.eyebrow": "Section · Waste",
    "waste.statItemsLogged": "Items logged",
    "waste.statEstimatedLoss": "Estimated loss",
    "waste.statThisMonth": "This month",
    "waste.statMostWasted": "Most wasted",
    "waste.statLifetime": "lifetime",
    "waste.statEntries": "entries",
    "waste.statTimesWasted": "× wasted",
    "waste.statNoData": "no data yet",
    "waste.weeklyTrend": "Weekly trend",
    "waste.byCategory": "By category",
    "waste.repeatOffenders": "Repeat offenders",
    "waste.startTracking": "Start tracking · trend appears here",
    "waste.cleanLedger": "Clean ledger",
    "waste.nothingWasted": "Nothing wasted yet",
    "waste.recentLog": "Recent log · last 10 entries",
    "waste.emptyTitle": "Nothing wasted yet.",
    "waste.emptyBody": "Mark items as wasted when they spoil — patterns surface here so you can shop smaller next time.",
    "waste.total": "total",

    // recipes
    "recipes.eyebrow": "Section · Kitchen Desk",
    "recipes.title": "Recipes",
    "recipes.subtitle": "A daily column of what you can cook with what's already in the larder.",
    "recipes.fileRecipe": "File a recipe",
    "recipes.briefing": "Briefing",
    "recipes.filterAll": "All",
    "recipes.filterZeroWaste": "No shopping needed",
    "recipes.filterAlmostThere": "Almost there (≤2 missing)",
    "recipes.filterLabel": "Filter ·",
    "recipes.tabSaved": "Saved",
    "recipes.tabClassic": "Classic",
    "recipes.tabAI": "AI",
    "recipes.pantryCheck": "Pantry check",
    "recipes.have": "have",
    "recipes.need": "need",
    "recipes.min": "min",
    "recipes.servings": "servings",
    "recipes.match": "match",
    "recipes.adding": "Adding…",
    "recipes.addedToList": "Added to list",
    "recipes.addToList": "to list",
    "recipes.saved": "Saved",
    "recipes.saving": "Saving…",
    "recipes.saveFavourite": "Save favourite",
    "recipes.removing": "Removing…",
    "recipes.remove": "Remove",
    "recipes.reduceQuantities": "Reduce quantities?",
    "recipes.yes": "Yes",
    "recipes.no": "No",
    "recipes.filingChanges": "Filing changes…",
    "recipes.cooked": "Cooked",
    "recipes.hideMethod": "Hide the method",
    "recipes.readMethod": "Read the method",
    "recipes.recipePreferences": "Recipe preferences",
    "recipes.editorialBriefing": "Editorial briefing",
    "recipes.cancel": "Cancel",
    "recipes.filing": "Filing…",
    "recipes.saveApply": "Save & apply",
    "recipes.mealGoal": "Sub · 01 · meal goal",
    "recipes.caloriesServing": "Sub · 02 · calories / serving",
    "recipes.proteinServing": "Sub · 03 · protein / serving",
    "recipes.dietaryRestrictions": "Sub · 04 · dietary restrictions",
    "recipes.servingsLabel": "Sub · 05 · servings",
    "recipes.goalQuickEnergy": "Quick Energy",
    "recipes.goalHighProtein": "High Protein",
    "recipes.goalLight": "Light",
    "recipes.goalBalanced": "Balanced",
    "recipes.goalComfort": "Comfort",
    "recipes.calLight": "Light",
    "recipes.calModerate": "Moderate",
    "recipes.calHearty": "Hearty",
    "recipes.protLow": "Low",
    "recipes.protModerate": "Moderate",
    "recipes.protHigh": "High",
    "recipes.dietVegetarian": "Vegetarian",
    "recipes.dietVegan": "Vegan",
    "recipes.dietGlutenFree": "Gluten-free",
    "recipes.dietDairyFree": "Dairy-free",
    "recipes.dietNutFree": "Nut-free",
    "recipes.dietLowSodium": "Low sodium",
    "recipes.formRecipeName": "01 · Recipe name",
    "recipes.formPrepTime": "02 · Prep time (min)",
    "recipes.formServings": "03 · Servings",
    "recipes.formIngredients": "04 · Ingredients · one per line",
    "recipes.formIngredientsHint": "Pantry items, raw",
    "recipes.formInstructions": "05 · Method · one step per line",
    "recipes.formInstructionsHint": "Numbered when displayed",
    "recipes.formTags": "06 · Tags · comma-separated",
    "recipes.formTitlePlaceholder": "Tuesday tomato pasta",
    "recipes.formTagsPlaceholder": "quick, dinner, leftover-friendly",
    "recipes.filingRecipe": "Filing the recipe…",
    "recipes.fileThisRecipe": "File this recipe",
    "recipes.addYourRecipe": "Add your recipe",
    "recipes.onTheWire": "On the wire",
    "recipes.aiComposing": "Claude is composing recipes for your larder.",
    "recipes.apiKeyRequired": "API key required",
    "recipes.stopPress": "Stop press",
    "recipes.retry": "Retry",
    "recipes.refresh": "Refresh",
    "recipes.aiMacrosEstimated": "AI · macros estimated per serving",
    "recipes.aiCached": "Cached · AI · macros estimated per serving",
    "recipes.noSavedMatchFilter": "No saved recipes match this filter.",
    "recipes.noSavedMatchFilterBody": "Try a different filter or save a new recipe.",
    "recipes.noSavedRecipes": "No saved recipes yet.",
    "recipes.noSavedRecipesBody": "Add your own household recipes or save favourites from the AI tab.",
    "recipes.noClassicMatchFilter": "No recipes match this filter.",
    "recipes.noClassicMatchFilterBody": "Try a different filter or add more items to your inventory.",
    "recipes.noClassicRecipes": "No recipe matches yet.",
    "recipes.noClassicRecipesBody": "Add more items to your inventory and we'll match you with recipes you can cook right now.",
    "recipes.addItems": "Add items",
    "recipes.noAIMatchFilter": "No recipes match this filter.",
    "recipes.noAIMatchFilterBody": "Try a different filter or refresh the AI.",
    "recipes.inventoryEmpty": "Your inventory is empty.",
    "recipes.inventoryEmptyBody": "Add some food items first and Claude will suggest recipes tailored to what you have.",
    "recipes.edit": "Edit",
    "recipes.close": "Close",
    "recipes.configKicker": "Configuration · stop press",
  },
  nb: {
    "nav.dashboard": "Oversikt",
    "nav.food": "Min mat",
    "nav.scan": "Skann strekkode",
    "nav.shopping": "Handleliste",
    "nav.deals": "Tilbud og priser",
    "nav.recipes": "Oppskrifter",
    "nav.waste": "Matsvinn",
    "nav.settings": "Innstillinger",
    "settings.title": "Innstillinger",
    "settings.subtitle": "Administrer husholdning og preferanser",
    "settings.appearanceLanguage": "Utseende og språk",
    "settings.appearanceTitle": "Apppreferanser",
    "settings.appearanceDescription": "Velg språk for grensesnittet og hvordan FreshTrack skal bruke lys eller mørk modus.",
    "settings.language": "Språk",
    "settings.theme": "Tema",
    "settings.themeLight": "Lys",
    "settings.themeDark": "Mørk",
    "settings.themeSystem": "System",
    "settings.languageEnglish": "Engelsk",
    "settings.languageNorwegian": "Norsk bokmål",
    "settings.savedLocally": "Lagres på denne enheten og brukes med en gang.",
    "dashboard.kicker": "Oversikt",
    "dashboard.title": "Dagens kjøleskapsrapport.",
    "dashboard.subtitle": "Den nyttige versjonen av å åpne kjøleskapet tre ganger og håpe at det forteller deg hva du bør lage.",
    "dashboard.totalItems": "Totalt antall",
    "dashboard.inFridge": "I kjøleskap",
    "dashboard.inFreezer": "I fryser",
    "dashboard.expiringSoon": "Går snart ut",
    "dashboard.useSoon": "Bruk dette snart",
    "dashboard.viewAll": "Vis alle",
    "dashboard.nextReminder": "Neste påminnelse",
    "dashboard.tuneSettings": "Juster innstillinger",
    "dashboard.groceryInsights": "Handleinnsikt",
    "dashboard.quickActions": "Snarveier",
    "dashboard.manageFood": "Administrer mat",
    "dashboard.manageFoodDesc": "Legg til, endre eller fjern varer fra lageret",
    "dashboard.scanBarcode": "Skann strekkode",
    "dashboard.scanBarcodeDesc": "Legg til varer raskt ved å skanne strekkoder",
    "dashboard.findRecipes": "Finn oppskrifter",
    "dashboard.findRecipesDesc": "Se hva du kan lage med det du har",
    "dashboard.open": "Åpne",
    "shopping.title": "Handleliste",
    "shopping.remaining": "gjenstår",
    "shopping.cheapestOverall": "Billigst totalt",
    "shopping.checking": "Sjekker…",
    "shopping.pasteList": "Lim inn liste",
    "shopping.addItem": "Legg til vare",
    "shopping.newList": "Ny liste",
    "shopping.rename": "Gi nytt navn",
    "shopping.setDefault": "Sett som standard",
    "shopping.delete": "Slett",
    "shopping.groceryRecap": "Handleoppsummering",
    "shopping.boughtThisMonth": "Kjøpt denne måneden",
    "shopping.mostBoughtCategory": "Mest kjøpte kategori",
    "shopping.estimatedSpend": "Estimert forbruk",
    "shopping.topRepeatedItem": "Mest gjentatte vare",
    "shopping.quickAddPlaceholder": "Skriv varenavn og trykk Enter",
    "shopping.storeMode": "Butikkmodus",
    "shopping.storeModeDesc": "Fokuser på varer som ikke er huket av, med større mobilknapper.",
    "shopping.on": "På",
    "shopping.off": "Av",
    "shopping.category": "Kategori",
    "shopping.storeLayout": "Butikkrekkefølge",
    "shopping.sortedByAisle": "Sortert etter typisk butikkrunde",
    "shopping.emptyTitle": "Handlelisten er tom",
    "shopping.emptyDescription": "Legg til varer eller la FreshTrack foreslå påfyll fra lageret ditt.",
    "shopping.addFirstItem": "Legg til første vare",
    "shopping.checked": "Avhuket",
    "shopping.putAwayBought": "Legg inn kjøpte varer",
    "shopping.clearAll": "Tøm alle",
    "shopping.smartRestock": "Smart påfyll",
    "shopping.suggestedRestocks": "Foreslått påfyll",
    "shopping.expiringRestock": "Går snart ut — kjøpe mer?",
    "shopping.seasonalHolidays": "Sesong og høytider",
    "shopping.inSeasonNow": "I sesong nå",
    "shopping.inSeasonHint": "ofte billigere og ferskere",
    "shopping.browseHolidayLists": "Se alle høytidslister",
    "shopping.createList": "Opprett handleliste",
    "shopping.createListSubtitle": "Hold ulike handleturer adskilt",
    "shopping.cancel": "Avbryt",
    "shopping.create": "Opprett liste",
    "shopping.pasteTitle": "Lim inn handleliste",
    "shopping.pasteSubtitle": "Forhåndsvis notater, kommaseparerte lister eller én vare per linje før import",
    "shopping.previewItems": "Forhåndsvis varer",
    "shopping.import": "Importer",
    "shopping.items": "varer",
    "shopping.putAwaySubtitle": "Velg hvor hver vare skal ligge og se foreslått utløpsdato",
    "shopping.destination": "Plassering",
    "shopping.expiryEstimate": "Utløpsestimat",
    "shopping.confirmPutAway": "Bekreft innlegging",

    // deals
    "deals.eyebrow": "Seksjon · Markedsoversikt",
    "deals.title": "Tilbud og priser",
    "deals.subtitle": "Daglig oversikt over norske matvarepriser via Kassalapp.",
    "deals.tabDeals": "Tilbud",
    "deals.tabDrops": "Prisfall",
    "deals.tabSearch": "Søk",
    "deals.tabStores": "Butikker",
    "deals.bestBasket": "Forsiden · beste handlekurv",
    "deals.kroner": "kroner",
    "deals.runnersUp": "Nestbest · oversikt",
    "deals.itemsOf": "av",
    "deals.items": "varer",
    "deals.filterChains": "Filtrer kjeder",
    "deals.clear": "Nullstill",
    "deals.addToList": "Legg til liste",
    "deals.usePrice": "Bruk pris",
    "deals.best": "Best",
    "deals.loadingDeals": "Sjekker kurven mot prisene…",
    "deals.loadingDrops": "Skanner ledningene for prisfall…",
    "deals.loadingSearch": "Søker priser…",
    "deals.searchPlaceholder": "Søk i norske butikkhyller…",
    "deals.fileSearch": "Søk",
    "deals.noDrops": "Ingen prisfall registrert",
    "deals.noDropsBody": "Ingenting merkbart billigere de siste 30 dagene.",
    "deals.noDeals": "Ingen tilbud å vise",
    "deals.noDealsBody": "Legg til varer i handlelisten først, så henter vi dagens beste priser.",
    "deals.noProducts": "Ingen produkter funnet",
    "deals.noProductsBody": "Prøv et annet søkeord.",
    "deals.noStoreMatch": "Ingen produkter fra valgte butikker.",
    "deals.storesNearbyKicker": "Seksjon · Butikker i nærheten",
    "deals.storesNearbyTitle": "Finn nærmeste hyllene.",
    "deals.storesNearbyBody": "Bruk posisjonen din til å kartlegge alle norske dagligvarekjeder innen fem kilometer.",
    "deals.gettingLocation": "Henter posisjon…",
    "deals.findingStores": "Finner butikker…",
    "deals.useMyLocation": "Bruk min posisjon",
    "deals.refresh": "Oppdater",
    "deals.noStores": "Ingen butikker i nærheten",
    "deals.noStoresBody": "Prøv å utvide søkeradius.",
    "deals.stopPress": "Stopp pressen",
    "deals.configNeeded": "Konfigurasjon mangler",
    "deals.somethingWrong": "Noe gikk galt",
    "deals.getFreeKey": "Hent gratis API-nøkkel på",
    "deals.options": "alternativ",
    "deals.optionsPlural": "alternativer",
    "deals.directions": "Veibeskrivelse",
    "deals.within5km": "innen 5 km",
    "deals.sessionExpired": "Økt utløpt, omdirigerer til innlogging…",
    "deals.dropsHeader": "prisfall siste 30 dager",
    "deals.plateDropsKicker": "Plate · 02 · prisfall siste 30 dager",
    "deals.plateStoresKicker": "Plate · 04 · innen 5 km",
    "deals.itemPrefix": "Vare ·",
    "deals.notice": "Notis",
    "deals.toastAddedSuffix": "lagt til handlelisten",
    "deals.toastFailedAdd": "Kunne ikke legge til i listen",
    "deals.toastPriceFiled": "Pris registrert i handlelisten",
    "deals.toastFailedSave": "Kunne ikke lagre pris",
    "deals.toastFailedFindStores": "Fant ikke butikker",
    "deals.toastGeoNotSupported": "Posisjonstjenester støttes ikke av nettleseren",
    "deals.toastLocationFailed": "Kunne ikke hente posisjon",

    // scan
    "scan.title": "Skann strekkode",
    "scan.subtitle": "Pek kameraet mot en strekkode for å legge til raskt",
    "scan.opticalKicker": "Optisk · strekkodelesing",
    "scan.statusLive": "aktiv",
    "scan.statusReady": "klar",
    "scan.statusFault": "feil",
    "scan.statusIdle": "inaktiv",
    "scan.scanning": "Skanner",
    "scan.cameraPreview": "Kameravisning vises her",
    "scan.aimAtBarcode": "Pek mot en strekkode",
    "scan.startCamera": "Start kamera",
    "scan.cameraUnavailable": "Kamera utilgjengelig",
    "scan.tryAgain": "Prøv igjen",
    "scan.stop": "Stopp",
    "scan.lookingUp": "slår opp produkt",
    "scan.orEnterManually": "Eller · skriv inn manuelt",
    "scan.typeBarcode": "Skriv strekkoden",
    "scan.lookUp": "Slå opp",
    "scan.skipManual": "Hopp over · legg til manuelt",
    "scan.addScannedItem": "Legg til skannet vare",
    "scan.addItemManually": "Legg til vare manuelt",
    "scan.barcodePrefix": "Strekkode",
    "scan.barcodePlaceholder": "0 0 0 0 0 0 0 0 0 0 0 0",
    "scan.cameraError": "Kameraet er blokkert. Tillat kameratilgang for å skanne strekkoder.",
    "scan.toastFailedAdd": "Kunne ikke legge til vare",

    // waste
    "waste.title": "Matsvinnlogg",
    "waste.subtitle": "En ærlig oversikt over det som ikke nådde bordet",
    "waste.eyebrow": "Seksjon · Matsvinn",
    "waste.statItemsLogged": "Registrerte varer",
    "waste.statEstimatedLoss": "Estimert tap",
    "waste.statThisMonth": "Denne måneden",
    "waste.statMostWasted": "Mest kastet",
    "waste.statLifetime": "totalt",
    "waste.statEntries": "oppføringer",
    "waste.statTimesWasted": "× kastet",
    "waste.statNoData": "ingen data ennå",
    "waste.weeklyTrend": "Ukentlig trend",
    "waste.byCategory": "Etter kategori",
    "waste.repeatOffenders": "Gjengangere",
    "waste.startTracking": "Start registrering · trend vises her",
    "waste.cleanLedger": "Ren bok",
    "waste.nothingWasted": "Ingenting kastet ennå",
    "waste.recentLog": "Siste logg · 10 siste oppføringer",
    "waste.emptyTitle": "Ingenting kastet ennå.",
    "waste.emptyBody": "Merk varer som kastet når de ødelegger seg — mønstre vises her så du kan handle smartere.",
    "waste.total": "totalt",

    // recipes
    "recipes.eyebrow": "Seksjon · Kjøkkendesk",
    "recipes.title": "Oppskrifter",
    "recipes.subtitle": "Daglig oversikt over hva du kan lage med det som allerede er i skapet.",
    "recipes.fileRecipe": "Legg inn oppskrift",
    "recipes.briefing": "Briefing",
    "recipes.filterAll": "Alle",
    "recipes.filterZeroWaste": "Ingen handling nødvendig",
    "recipes.filterAlmostThere": "Nesten (≤2 mangler)",
    "recipes.filterLabel": "Filter ·",
    "recipes.tabSaved": "Lagrede",
    "recipes.tabClassic": "Klassisk",
    "recipes.tabAI": "AI",
    "recipes.pantryCheck": "Lagerkontroll",
    "recipes.have": "har",
    "recipes.need": "mangler",
    "recipes.min": "min",
    "recipes.servings": "porsjoner",
    "recipes.match": "treff",
    "recipes.adding": "Legger til…",
    "recipes.addedToList": "Lagt til liste",
    "recipes.addToList": "til liste",
    "recipes.saved": "Lagret",
    "recipes.saving": "Lagrer…",
    "recipes.saveFavourite": "Lagre favoritt",
    "recipes.removing": "Fjerner…",
    "recipes.remove": "Fjern",
    "recipes.reduceQuantities": "Reduser mengder?",
    "recipes.yes": "Ja",
    "recipes.no": "Nei",
    "recipes.filingChanges": "Registrerer endringer…",
    "recipes.cooked": "Laget",
    "recipes.hideMethod": "Skjul fremgangsmåte",
    "recipes.readMethod": "Vis fremgangsmåte",
    "recipes.recipePreferences": "Oppskriftspreferanser",
    "recipes.editorialBriefing": "Redaksjonell briefing",
    "recipes.cancel": "Avbryt",
    "recipes.filing": "Registrerer…",
    "recipes.saveApply": "Lagre og bruk",
    "recipes.mealGoal": "Del · 01 · måltidsmål",
    "recipes.caloriesServing": "Del · 02 · kalorier / porsjon",
    "recipes.proteinServing": "Del · 03 · protein / porsjon",
    "recipes.dietaryRestrictions": "Del · 04 · kostholdsbegrensninger",
    "recipes.servingsLabel": "Del · 05 · porsjoner",
    "recipes.goalQuickEnergy": "Rask energi",
    "recipes.goalHighProtein": "Høy protein",
    "recipes.goalLight": "Lett",
    "recipes.goalBalanced": "Balansert",
    "recipes.goalComfort": "Comfort",
    "recipes.calLight": "Lett",
    "recipes.calModerate": "Moderat",
    "recipes.calHearty": "Solid",
    "recipes.protLow": "Lav",
    "recipes.protModerate": "Moderat",
    "recipes.protHigh": "Høy",
    "recipes.dietVegetarian": "Vegetar",
    "recipes.dietVegan": "Vegan",
    "recipes.dietGlutenFree": "Glutenfri",
    "recipes.dietDairyFree": "Laktosefri",
    "recipes.dietNutFree": "Nøttefri",
    "recipes.dietLowSodium": "Lite salt",
    "recipes.formRecipeName": "01 · Oppskriftsnavn",
    "recipes.formPrepTime": "02 · Tilberedningstid (min)",
    "recipes.formServings": "03 · Porsjoner",
    "recipes.formIngredients": "04 · Ingredienser · én per linje",
    "recipes.formIngredientsHint": "Råvarer, enkle",
    "recipes.formInstructions": "05 · Fremgangsmåte · ett steg per linje",
    "recipes.formInstructionsHint": "Nummerert ved visning",
    "recipes.formTags": "06 · Tags · kommaseparert",
    "recipes.formTitlePlaceholder": "Tirsdagspasta med tomat",
    "recipes.formTagsPlaceholder": "rask, middag, restemat",
    "recipes.filingRecipe": "Registrerer oppskrift…",
    "recipes.fileThisRecipe": "Legg inn oppskrift",
    "recipes.addYourRecipe": "Legg inn oppskrift",
    "recipes.onTheWire": "På ledningen",
    "recipes.aiComposing": "Claude komponerer oppskrifter til skapet ditt.",
    "recipes.apiKeyRequired": "API-nøkkel mangler",
    "recipes.stopPress": "Stopp pressen",
    "recipes.retry": "Prøv igjen",
    "recipes.refresh": "Oppdater",
    "recipes.aiMacrosEstimated": "AI · makronæring estimert per porsjon",
    "recipes.aiCached": "Mellomlagret · AI · makronæring estimert per porsjon",
    "recipes.noSavedMatchFilter": "Ingen lagrede oppskrifter matcher dette filteret.",
    "recipes.noSavedMatchFilterBody": "Prøv et annet filter eller lagre en ny oppskrift.",
    "recipes.noSavedRecipes": "Ingen lagrede oppskrifter ennå.",
    "recipes.noSavedRecipesBody": "Legg inn egne oppskrifter eller lagre favoritter fra AI-fanen.",
    "recipes.noClassicMatchFilter": "Ingen oppskrifter matcher dette filteret.",
    "recipes.noClassicMatchFilterBody": "Prøv et annet filter eller legg til flere varer i lageret.",
    "recipes.noClassicRecipes": "Ingen oppskriftstreff ennå.",
    "recipes.noClassicRecipesBody": "Legg til flere varer i lageret, så finner vi oppskrifter du kan lage nå.",
    "recipes.addItems": "Legg til varer",
    "recipes.noAIMatchFilter": "Ingen oppskrifter matcher dette filteret.",
    "recipes.noAIMatchFilterBody": "Prøv et annet filter eller oppdater AI.",
    "recipes.inventoryEmpty": "Lageret er tomt.",
    "recipes.inventoryEmptyBody": "Legg til matvarer først, så foreslår Claude oppskrifter tilpasset det du har.",
    "recipes.edit": "Endre",
    "recipes.close": "Lukk",
    "recipes.configKicker": "Konfigurasjon · stopp pressen",
  },
};

interface AppPreferencesContextValue {
  language: AppLanguage;
  theme: AppTheme;
  resolvedTheme: "light" | "dark";
  setLanguage: (language: AppLanguage) => void;
  setTheme: (theme: AppTheme) => void;
  t: (key: TranslationKey) => string;
}

const AppPreferencesContext = createContext<AppPreferencesContextValue | null>(null);

function getInitialPreferences(): { language: AppLanguage; theme: AppTheme } {
  if (typeof window === "undefined") return { language: "en", theme: "system" };

  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored) as Partial<{ language: AppLanguage; theme: AppTheme }>;
      return {
        language: parsed.language === "nb" ? "nb" : "en",
        theme: parsed.theme === "light" || parsed.theme === "dark" || parsed.theme === "system" ? parsed.theme : "system",
      };
    }
  } catch {
    // Ignore malformed local preferences and fall back to defaults.
  }

  const browserLanguage = navigator.language.toLowerCase().startsWith("no") || navigator.language.toLowerCase().startsWith("nb")
    ? "nb"
    : "en";
  return { language: browserLanguage, theme: "system" };
}

export function AppPreferencesProvider({ children }: { children: React.ReactNode }) {
  const [preferences, setPreferences] = useState(getInitialPreferences);
  const [systemTheme, setSystemTheme] = useState<"light" | "dark">("light");

  useEffect(() => {
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const update = () => setSystemTheme(media.matches ? "dark" : "light");
    update();
    media.addEventListener("change", update);
    return () => media.removeEventListener("change", update);
  }, []);

  const resolvedTheme = preferences.theme === "system" ? systemTheme : preferences.theme;

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences));
  }, [preferences]);

  useEffect(() => {
    const root = document.documentElement;
    root.lang = preferences.language === "nb" ? "nb" : "en";
    root.dataset.theme = resolvedTheme;
    root.classList.toggle("theme-dark", resolvedTheme === "dark");
  }, [preferences.language, resolvedTheme]);

  const value = useMemo<AppPreferencesContextValue>(() => ({
    language: preferences.language,
    theme: preferences.theme,
    resolvedTheme,
    setLanguage: (language) => setPreferences((current) => ({ ...current, language })),
    setTheme: (theme) => setPreferences((current) => ({ ...current, theme })),
    t: (key) => TRANSLATIONS[preferences.language][key] ?? TRANSLATIONS.en[key] ?? key,
  }), [preferences.language, preferences.theme, resolvedTheme]);

  return (
    <AppPreferencesContext.Provider value={value}>
      {children}
    </AppPreferencesContext.Provider>
  );
}

export function useAppPreferences() {
  const context = useContext(AppPreferencesContext);
  if (!context) {
    throw new Error("useAppPreferences must be used within AppPreferencesProvider");
  }
  return context;
}
