// Generated by `npm run cf-typegen` — do not edit manually
// Run: wrangler types

interface Env {
  DB: D1Database;
  ANTHROPIC_API_KEY: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  APP_ENV: string;
  /** Kassalapp API key — get yours free at https://kassal.app/api */
  KASSALAPP_API_KEY: string;
}
